# Generated by Django 3.0.4 on 2020-03-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200319_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressinfo',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='zipcode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
